[versions]

junit = "5.8.1"
jetbrains_annotations = "24.0.1"
autoservice = "1.0.1"

groovy = "4.0.15"
asm = "9.4"

managedversioning = "1.1.0"
nexuspublish = "1.3.0"

[libraries]

junit_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

jetbrains_annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains_annotations" }
autoservice = { module = "com.google.auto.service:auto-service", version.ref = "autoservice" }

groovy_core = { module = "org.apache.groovy:groovy", version.ref = "groovy" }

asm = { module = "org.ow2.asm:asm", version.ref = "asm" }

[plugins]

managedversioning = { id = "dev.lukebemish.managedversioning", version.ref = "managedversioning" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }