name: Build PR
concurrency: ci-${{ github.ref }}
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          cache-read-only: ${{ !startsWith(github.ref, 'refs/heads/1.') }}
      - name: Build
        run: |
          ./gradlew build
      - name: Publish
        run: |
          ./gradlew publish
      - name: Archive publishable artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: build/repo
          retention-days: 1
      - name: Test
        run: |
          ./gradlew test
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: junit-test-results
          path: "*/build/test-results/test/TEST-*.xml"
          retention-days: 1