name: Build Natives
on:
  push:
    branches:
      - natives
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Bazel
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - run: bazelisk build //java:libopensesamenatives-src.jar
      - uses: actions/upload-artifact@v4
        with:
          name: sources
          path: bazel-bin/java/libopensesamenatives-src.jar
  build-natives:
    strategy:
      matrix:
        runner: [{"linux": "ubuntu-latest", "windows": "ubuntu-latest", "macos": "macos-latest"}]
        libname: [{"linux": "libopensesamenative.so", "windows": "opensesamenative.dll", "macos": "libopensesamenative.dynlib"}]
        arch:
          - i386
          - x86_64
          - aarch64
        include:
          - os: linux
          - arch: arm
        exclude:
          - os: macos
          - arch: i386
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Bazel - MacOs
        if: ${{ matrix.runner[matrix.os] }} == 'macos-latest'
        uses: actions/cache@v4
        with:
          path: |
            /private/var/tmp/_bazel_runner/
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Cache Bazel - Linux
        if: ${{ matrix.runner[matrix.os] }} == 'ubuntu-latest'
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'WORKSPACE', 'WORKSPACE.bazel', 'MODULE.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - run: bazelisk build //cpp:opensesamenatives --platforms=//platform:${{ matrix.os }}_${{ matrix.arch }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.arch }}
          path: bazel-bin/cpp/${{ matrix.libname[matrix.os] }}