name: Release
concurrency: ci-${{ github.ref }}
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
      - name: Tag Release
        run: |
          ./gradlew tagRelease
      - name: Build
        run: |
          ./gradlew build
      - name: Publish
        run: |
          ./gradlew release closeAndReleaseSonatypeStagingRepository
        env:
          IS_RELEASE: true
          MAVEN_USER: github
          MAVEN_PASSWORD: ${{ secrets.RELEASE_MAVEN_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSWORD }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PLUGIN_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PLUGIN_SECRET }}
      - run: |
          git push
          git push --tags
      - name: Submit Dependencies
        uses: mikepenz/gradle-dependency-submission@v0.9.0
        with:
          gradle-build-module: |-
            :opensesame-core
            :opensesame-compile
            :opensesame-groovy
            :opensesame-javac
          gradle-build-configuration: |-
            compileClasspath