name: Report Test Results
on:
  workflow_run:
    workflows: [Build PR, Snapshot]
    types: [completed]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: junit-test-results
      - name: JUnit Test Report - Java 17
        uses: dorny/test-reporter@v1
        with:
          name: Test Results - Java 17
          path: "**/test-results/testOn17/**/TEST-*.xml,**/test-results/test/**/TEST-*.xml"
          reporter: java-junit
          fail-on-empty: 'true'
          list-tests: 'failed'
      - name: JUnit Test Report - Java 21
        uses: dorny/test-reporter@v1
        with:
          name: Test Results - Java 21
          path: "**/test-results/testOn21/**/TEST-*.xml"
          reporter: java-junit
          fail-on-empty: 'true'
          list-tests: 'failed'
      - name: JUnit Test Report - Misc
        uses: dorny/test-reporter@v1
        with:
          name: Test Results - Misc
          path: "**/test-results/test/**/TEST-*.xml"
          reporter: java-junit
          fail-on-empty: 'true'
          list-tests: 'failed'