{
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "permissions": {
                "packages": "read"
            },
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_17_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0",
                        "persist-credentials": "false"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "name": "Validate Gradle Wrapper",
                    "uses": "gradle/actions/wrapper-validation@v3"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache\n**/.gradle/quilt-loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache/restore@v4"
                },
                {
                    "with": {
                        "cache-read-only": true,
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/actions/setup-gradle@v3"
                },
                {
                    "name": "Assemble",
                    "run": "./gradlew assemble",
                    "id": "assemble",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    }
                },
                {
                    "name": "Test",
                    "run": "./gradlew check --continue",
                    "id": "test",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    }
                },
                {
                    "name": "Test Plugin",
                    "run": "./gradlew check --continue",
                    "id": "test_plugin",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    },
                    "working-directory": "./testplugin",
                    "if": "(success() || failure()) && steps.assemble.outcome == 'success'"
                },
                {
                    "with": {
                        "name": "junit-test-results",
                        "path": "**/build/test-results/*/TEST-*.xml",
                        "retention-days": "1"
                    },
                    "name": "Upload junit-test-results",
                    "uses": "actions/upload-artifact@v4",
                    "if": "(success() || failure()) && steps.assemble.outcome == 'success'"
                },
                {
                    "name": "Publish",
                    "run": "./gradlew publish",
                    "id": "publish",
                    "env": {
                        "BUILD_CACHE_PASSWORD": "${{ secrets.BUILD_CACHE_PASSWORD }}",
                        "BUILD_CACHE_USER": "${{ secrets.BUILD_CACHE_USER }}",
                        "BUILD_CACHE_URL": "${{ secrets.BUILD_CACHE_URL }}",
                        "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}",
                        "SNAPSHOT_MAVEN_PASSWORD": "${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}",
                        "SNAPSHOT_MAVEN_USER": "github",
                        "SNAPSHOT_MAVEN_URL": "https://maven.lukebemish.dev/snapshots/"
                    }
                }
            ]
        }
    },
    "name": "Snapshot",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "workflow_dispatch": {
            
        },
        "push": {
            "branches": [
                "main"
            ]
        }
    }
}