name: Snapshot
concurrency: ci-${{ github.ref }}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_17_X64" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
      - name: Build
        id: build
        run: |
          ./gradlew build
      - name: Publish
        run: |
          ./gradlew publish
        env:
          MAVEN_USER: github
          MAVEN_PASSWORD: ${{ secrets.SNAPSHOT_MAVEN_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SNAPSHOT_MAVEN_URL: https://maven.lukebemish.dev/snapshots/
      - name: Test
        run: |
          ./gradlew test
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        if: (success() || failure()) && steps.build.conclusion == 'success'
        with:
          name: junit-test-results
          path: "*/build/test-results/test/TEST-*.xml"
          retention-days: 1
